WEB-BilgeAdam/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace WEB_BilgeAdam.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WEB-BilgeAdam/Controllers/StudentsController.cs
using ApplicationCore_BilgeAdam.DTO_s.ClassroomDTO;
using ApplicationCore_BilgeAdam.DTO_s.StudentDTO;
using ApplicationCore_BilgeAdam.Entities.Concrete;
using ApplicationCore_BilgeAdam.Entities.UserEntities.Concrete;
using AutoMapper;
using Infrastructure_BilgeAdam.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WEB_BilgeAdam.Models.ViewModels;

namespace WEB_BilgeAdam.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentRepository _studentRepo;
        private readonly IMapper _mapper;
        private readonly IClassroomRepository _classroomRepo;
        private readonly ITeacherRepository _teacherRepo;
        private readonly UserManager<AppUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public StudentsController(IStudentRepository studentRepo, IMapper mapper, IClassroomRepository classroomRepo, ITeacherRepository teacherRepo, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _studentRepo = studentRepo;
            _mapper = mapper;
            _classroomRepo = classroomRepo;
            _teacherRepo = teacherRepo;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var students = await _studentRepo.GetFilteredList
                (
                    select: x => new StudentVM
                    {
                        Id = x.Id,
                        FirstName = x.FirstName,
                        LastName = x.LastName,
                        BirthDate = x.BirthDate,
                        Email = x.Email,
                        ClassroomName = x.Classroom.ClassroomName,
                        Average = x.Average,
                        CreatedDate = x.CreatedDate,
                        UpdatedDate = x.UpdatedDate
                    },
                    where: x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive,
                    orderBy: x => x.OrderByDescending(z => z.CreatedDate),
                    join: x => x.Include(z => z.Classroom)
                );

            return View(students);
        }

        public async Task<IActionResult> CreateStudent()
        {
            var model = new CreateStudentDTO
            {
                Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive)

            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateStudent(CreateStudentDTO model)
        {
            model.Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
            if (ModelState.IsValid)
            {
                var student = _mapper.Map<Student>(model);
                await _studentRepo.AddAsync(student);
                TempData["Success"] = $"{student.FirstName} {student.LastName} öğrencisi sisteme kayıt edilmiştir!";
                return RedirectToAction("Index");
            }
            TempData["Error"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        public async Task<IActionResult> UpdateStudent(int id)
        {
            if (id > 0)
            {
                var student = await _studentRepo.GetById(id);
                if (student != null)
                {
                    var model = _mapper.Map<UpdateStudentDTO>(student);
                    model.Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
                    return View(model);
                }
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStudent(UpdateStudentDTO model)
        {
            model.Classrooms = await _classroomRepo.GetByDefaults(x => x.Status != ApplicationCore_BilgeAdam.Entities.Abstract.Status.Passive);
            if (ModelState.IsValid)
            {
                var student = _mapper.Map<Student>(model);
                await _studentRepo.UpdateAsync(student);
                TempData["Success"] = $"{student.FirstName} {student.LastName} adlı öğrenci güncellenmiştir!";
                return RedirectToAction("Index");
            }
            TempData["Warning"] = "Lütfen aşağıdaki kurallara uyunuz!";
            return View(model);
        }

        public async Task<IActionResult> DeleteStudent(int id)
        {
            if (id > 0)
            {
                var student = await _studentRepo.GetById(id);
                if (student != null)
                {
                    await _studentRepo.DeleteAsync(student);
                    TempData["Success"] = "Öğrenci silinmiştir!";
                    return RedirectToAction("Index");
                }
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ShowStudentClassroom(string userName)
        {
            var appUser = await _userManager.FindByNameAsync(userName);

            var student = await _studentRepo.GetByDefault(x => x.Email == appUser.Email);
            if (student != null)
            {
                var classroom = await _classroomRepo.GetById(student.ClassroomId);
                var teacher = await _teacherRepo.GetById(classroom.TeacherId);
                if (classroom is not null)
                {
                    var model = _mapper.Map<ClassroomStudentDTO>(classroom);
                    model.TeacherName = teacher.FirstName + " " + teacher.LastName;
                    return View(model);
                }
            }
            TempData["Error"] = "Bir şeyler ters gitti!";
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> StudentExams(string userName)
        {
            var appUser = await _userManager.FindByNameAsync(userName);

            var student = await _studentRepo.GetByDefault(x => x.Email == appUser.Email);
            if (student != null)
            {
                var model = new StudentExamVM
                {
                    Exam1 = student.Exam1,
                    Exam2 = student.Exam2,
                    ProjectExam = student.ProjectExam,
                    ProjectPath = student.ProjectPath,
                    Average = student.Average
                };

                return View(model);
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> SetStudentExams(int id)
        {
            var student = await _studentRepo.GetById(id);
            if (student is not null)
            {
                var model = new StudentSetExamVM
                {
                    Id = student.Id,
                    FullName = student.FirstName + " " + student.LastName,
                    ClassroomId = student.ClassroomId
                };
                return View(model);
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("ShowClassrooms", "Teachers", new { userName = User.Identity.Name });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> SetStudentExams(StudentSetExamVM model)
        {
            var student = await _studentRepo.GetById(model.Id);
            if (student is not null) 
            {
                if (model.Exam1 != null)
                {
                    student.Exam1 = model.Exam1;
                }
                if (model.Exam2 != null)
                {
                    student.Exam2 = model.Exam2;
                }
                if (model.Project != null)
                {
                    string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "students/projects");
                    string fileName = $"{Guid.NewGuid()}_{student.FirstName}_{student.LastName}_{model.Project.FileName}";
                    string filePath = Path.Combine(uploadDir, fileName);
                    FileStream fileStream = new FileStream(filePath, FileMode.Create);
                    await model.Project.CopyToAsync(fileStream);
                    fileStream.Close();
                    student.ProjectPath = fileName;
                }
                if (model.ProjectExam != null)
                {
                    student.ProjectExam = model.ProjectExam;
                }
                await _studentRepo.UpdateAsync(student);
                TempData["Success"] = "Sınav notları başarılı bir şekilde girilmiştir!";
                return RedirectToAction("ShowClassroomForTeacher", "Teachers", new { id = student.ClassroomId });
            }
            TempData["Error"] = "Öğrenci bulunamadı!";
            return RedirectToAction("ShowClassrooms", "Teachers", new { userName = User.Identity.Name });
        }

        public ActionResult DownloadFile(string filePath)
        {
            string path = Path.Combine(_webHostEnvironment.WebRootPath, "students/projects/");
            byte[] fileBytes = System.IO.File.ReadAllBytes(path + filePath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, filePath);
        }
    }
}

WEB-BilgeAdam/Views/Shared/LayoutAlternative.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_BilgeAdam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_BilgeAdam.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="row mt-2 ms-2">
        <div class="col-md-3">
            <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="height:800px">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap" /></svg>
                    <span class="fs-4">@User?.Identity?.Name</span>
                </a>
                <hr>
                <ul class="nav nav-pills flex-column mb-auto">
                    @if (User.IsInRole("student"))
                    {
                        <li class="nav-item">
                            <a asp-controller="Students" asp-action="ShowStudentClassroom" asp-route-userName="@User.Identity.Name" class="nav-link active" aria-current="page">
                                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home" /></svg>
                                Sınıf Bilgileri
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Students" asp-action="StudentExams" asp-route-userName="@User.Identity.Name" class="nav-link text-white">
                                <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2" /></svg>
                                Notlar
                            </a>
                        </li>
                    }

                    else if (User.IsInRole("teacher"))
                    {
                        <li class="nav-item">
                            <a asp-controller="Teachers" asp-action="ShowClassrooms" asp-route-userName="@User?.Identity?.Name" class="nav-link active" aria-current="page">
                                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home" /></svg>
                                Sınıflar
                            </a>
                        </li>
                    }

                </ul>
                <hr>
                <div class="dropdown">
                    <a asp-controller="Account" asp-action="Edit" class="nav-link text-white">
                        <svg class="bi me-2" width="16" height="16"><use xlink:href="#table" /></svg>
                        Bilgileri Düzenle
                    </a>


                    <a class="nav-link text-white btn float-start" data-bs-toggle="modal" data-bs-target="#exampleModal">

                        <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid" /></svg>
                        Çıkış Yap
                    </a>

                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title  text-dark" id="exampleModalLabel">Çıkış Yapma Uyarısı</h5>
                                    <button type="button" class="btn-close  text-dark" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body  text-dark">
                                    Çıkış yapmak istediğinize emin misiniz?
                                </div>
                                <div class="modal-footer  text-dark">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">İptal</button>
                                    <a asp-controller="Account" asp-action="LogOut" type="button" class="btn btn-danger  text-white">Çıkış Yap</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <main role="main" class="pb-3 mt-4  ">
                <partial name="_NotificationPartial" />
                @RenderBody()
            </main>
        </div>
    </div>
    <div class="">
    </div>

    <footer class="border-top footer text-muted position-absolute bottom-0 d-flex align-items-center w-100" style="height:50px">
        <div class="container">
            &copy; 2023 - WEB_BilgeAdam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB-BilgeAdam/Views/Shared/_AuthenticationPartial.cshtml
@if (User?.Identity?.IsAuthenticated ?? false)
{
    <li class="nav-item ms-auto mx-2">
        <a asp-controller="Account" asp-action="Edit" class="btn btn-secondary">Kulllanıcı Bilgilerini Düzenle</a>
    </li>
    <li class="nav-item">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Çıkış Yap
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Çıkış Yapma Uyarısı</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Çıkış yapmak istediğinize emin misiniz?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">İptal</button>
                        <a asp-controller="Account" asp-action="LogOut" type="button" class="btn btn-danger">Çıkış Yap</a>
                    </div>
                </div>
            </div>
        </div>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-light btn btn-secondary" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin Paneli</a>
    </li>
    <li class="nav-item ms-auto mx-2">
        <a class="nav-link text-light btn btn-success" asp-area="" asp-controller="Account" asp-action="Register">Kayıt Ol</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-light btn btn-primary" asp-area="" asp-controller="Account" asp-action="Login">Giriş Yap</a>
    </li>
}

WEB-BilgeAdam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_BilgeAdam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_BilgeAdam.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BilgeAdam Öğrenci Portalı</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Öğretmenler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Öğrenciler</a>
                        </li>
                        <partial name="_AuthenticationPartial" />
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted position-absolute bottom-0 d-flex align-items-center w-100" style="height:50px">
        <div class="container">
            &copy; 2023 - WEB_BilgeAdam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB-BilgeAdam/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] is not null)
{
    <div class="alert alert-success notification">@TempData["Success"]</div>
}
@if (TempData["Warning"] is not null)
{
    <div class="alert alert-warning notification">@TempData["Warning"]</div>
}
@if (TempData["Error"] is not null)
{
    <div class="alert alert-danger notification">@TempData["Error"]</div>
}